json.(
  notification,
  :id,
  :event_id,
  :target,
  :has_responded,
  :has_accepted,
  :has_suggested_activity,
  :has_suggested_datetime,
  :has_suggested_location,
  :suggested_activity,
  :suggested_datetime,
  :suggested_location,
  :created_at,
  :updated_at
)